# basic options
title: Python for Newbies
author: kajtov
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
highlighter: rouge