# basic options
title: Python for Newbies
author: kajtov
email: ajtova.k@gmail.com  
description: Introduction to Python and data analysis. Step by step collection. 
github_username:  kajtov

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
highlighter: rouge

google_analytics: UA-106773929-1
